spring.application.name=OnThiGK_SpringBoot
# Thông tin kết nối MySQL trong Docker
spring.datasource.url=jdbc:mysql://localhost:3306/thigk_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Hibernate tự động tạo bảng (cần thiết cho bài thi)
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL trên console để dễ debug
spring.jpa.show-sql=true