server.port=8080

spring.ai.vertex.ai.gemini.base-url=https://generativelanguage.googleapis.com
spring.ai.vertex.ai.gemini.project-id=demo-project # Giá trị ảo, thư viện bắt buộc phải có
spring.ai.vertex.ai.gemini.location=us-central1 # Giá trị ảo

spring.ai.vertex.ai.gemini.api-key=AIzaSyDQYs8sgbKwGwwRqLBlZ9toMplonICRcKc

spring.ai.vertex.ai.gemini.chat.options.model=gemini-1.5-flash
spring.ai.vertex.ai.gemini.chat.options.temperature=0.4