server.port=8080
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.api-key=AIzaSyDQYs8sgbKwGwwRqLBlZ9toMplonICRcKc
spring.ai.openai.chat.options.model=gemini-1.5-flash