version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: thigk_mysql
    environment:
      MYSQL_DATABASE: thigk_db           # Tên database sẽ được tự động tạo
      MYSQL_ROOT_PASSWORD: root          # Mật khẩu tài khoản root
    ports:
      - "33012:3306"                      # Ánh xạ port 3306 của container ra ngoài máy thật
    volumes:
      - mysql_data:/var/lib/mysql        # Lưu trữ dữ liệu để không bị mất khi xóa container
    restart: unless-stopped              # Tự động khởi động lại nếu bị lỗi

volumes:
  mysql_data:                            # Khai báo volume